### ISSUE TITLE
Have Midway compute gains since parallel

### ISSUE THREAD

**Issue by tunnell** [XENON1T/cax#50]
Change this line::

`https://github.com/XENON1T/cax/blob/master/cax/tasks/corrections.py#L133`

To:

`midway-login1`

Then it should be parallel and speed up processing by days.

Since @coderdj implemented with Miguel a nice new SC API, we can now run this at places outside of LNGS.

**Comment by pdeperio** [comment]
Tried but get this error:
```
root        : INFO     Executing AddGains.
AddGains    : INFO     Run 4295: gains computing
AddGains    : INFO     Getting voltages at 1478192180
requests.packages.urllib3.connectionpool: INFO     Starting new HTTPS connection (1): xenon1t-daq.lngs.infn.it
/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/requests-2.9.1-py3.4.egg/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
AddGains    : ERROR    500 Server Error: Internal Server Error for url: https://xenon1t-daq.lngs.infn.it/slowcontrol/getLastMeasuredPMTValues
Traceback (most recent call last):
  File "/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/cax-4.5.2-py3.4.egg/cax/tasks/corrections.py", line 191, in get_voltages
    r.raise_for_status()
  File "/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/requests-2.9.1-py3.4.egg/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://xenon1t-daq.lngs.infn.it/slowcontrol/getLastMeasuredPMTValues
```

@coderdj @mcecilio ?

**Comment by pdeperio** [comment]
@tunnell I guess the API stuff needs to be merged for this?
